image: python:3.11

definitions:
  caches:
    platformio: ~/.platformio

pipelines:
  default:
    - step:
        name: "Build PlatformIO Firmware"
        caches:
          - pip
          - platformio
        script:
          - pip install -U platformio
          - pio run
